name: Deploy the app

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy through SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -tt -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" '
            # Go inside the app directory
            cd ~/

            # Get latest updates
            git fetch
            git checkout "${{ github.sha }}"

            # Install PHP dependencies
            composer install

            # Install JS dependencies
            yarn install

            # Build assets
            yarn build

            # Execute database migrations
            php bin/console doctrine:migrations:diff --allow-empty-diff
            php bin/console doctrine:migrations:migrate -n
          '
